# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginExercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginExercise
  pod 'SnapKit', '~> 5.6.0'  

  target 'LoginExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginExerciseUITests' do
    # Pods for testing
  end

end
